
require("melvin.plugins-setup")
require("melvin.core.options")
require("melvin.core.keymaps")
require("melvin.core.colorscheme")
require("melvin.plugins.comment")
require("melvin.plugins.nvim-tree")
require("melvin.plugins.lualine")
require("melvin.plugins.telescope")
require("melvin.plugins.nvim-cmp")
require("melvin.plugins.lsp.mason")
require("melvin.plugins.lsp.lspconfig")